
Neos:
  Flow:
    i18n:
      defaultLocale: en
  EventSourcedContentRepository:
    contentDimensions:
      language:
        label: Languages
        icon: icon-language
        defaultValue: en
        resolution:
          mode: 'uriPathSegment'
          options:
            allowEmptyValue: true
        values:
          en:
            label: 'English'
            resolution:
              value: ''

  Neos:
    userInterface:
      defaultLanguage: en
      translation:
        autoInclude:
          Neos.DocsNeosIo:
            - Main
            - 'NodeTypes/*'
